### ISSUE TITLE
Should Semiregular be decomposed, as in N3351 Appendix D.1

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#10]
Is EqualityComparable overconstraining?
What about Permutable requiring Semiregular?

**Comment by asutton** [comment]
> Is EqualityComparable overconstraining?

No.

> What about Permutable requiring Semiregular?

It probably could, but I haven't done my homework.

**Comment by CaseyCarter** [comment]
My initial thought was that decomposition into Movable and Copyable was inevitable to specify the containers, but in reality few of the container operations move/copy elements directly. `vector` reallocation is the obvious exception; `basic_string` operations are technically also an exception, but `basic_string` requires its elements to be POD. Container operations that move/copy construct elements do so indirectly via their allocators, and the existence of Movable/Copyable has no bearing on MoveInsertable/CopyInsertable. MoveAssignable/CopyAssignable are sufficient for the various flavors of container assignments.

The containers realistically provide little motivation for decomposing Semiregular.

**Comment by CaseyCarter** [comment]
I've given this some more thought in light of the discussion in #43. I would like to propose a decomposition that differs slightly from N3351. Currently in the TS, we have several "feature" concepts that describe individual properties of object types:
* Constructible
* DefaultConstructible
* MoveConstructible
* CopyConstructible
* Assignable
* MoveAssignable
* CopyAssignable

many of which are unusable in isolation, e.g., the capability to copy construct an object isn't useful if that copy cannot be destroyed. They exist to compose object types in the gaps between the concepts in the "object" hierarchy:
* Destructible
* Semiregular
* Regular

This is flexible, but awkward - not all combinations of "features" are sensible, and we end up with weird concepts like Function:
```
concept bool Function =
  Destructible<T> &&
  CopyConstructible<T> &&
  requires (F f, Args...args) {
    typename ResultType<F, Args...>;
    { &f } -> Same<F*>;
    { f.~F() } noexcept;
    { new F } -> Same<F*>;
    { delete new F };
    { f(forward<Args>(args)...) } -> Same<ResultType<F, Args...> >;
  };
```
This design violates one of the fundamental design ideals of N3351 (§1.3):
> The concepts used should express general ideas in the application domain (hence the name
“concepts”) rather than mere programming language artifacts. ... concepts should represent fully formed abstractions.

I propose killing two birds with one stone by eliminating what I have labeled "feature" concepts - with the exception of `Assignable` - and enlarging the set of "object" concepts to cover the useful combinations thereof. The design is based on a few precepts whose application to the decomposition of Semiregular results in a small family of "object" concepts that covers virtually all useful cases:

* Destruction is equivalent to deallocation.
```
template <class T>
concept bool Destructible =
  requires(T& t, T* p) {
    ( &t } -> Same<T*>;
    { t.~T() } noexcept;
    delete p;
    delete[] p; // Does this interact negatively with abstract classes?
  };
```

* Destruction is prerequisite to Construction, Construction is equivalent to allocation.
```
template <class T, class...Args>
concept bool Constructible =
  Destructible<T> &&
  requires(Args&&...args) {
    T{forward<Args>(args)...};
    { new T{forward<Args>(args)...} } -> Same<T*>;
  };

template <class T>
concept bool MoveConstructible =
  Constructible<T, T&&>;

template <class T>
concept bool CopyConstructible =
  MoveConstructible<T> &&
  Constructible<T, T&> &&
  Constructible<T, const T&> &&
  Constructible<T, const T&&>;
```

* Construction should be prerequisite to Assignment. If there's a way to transfer the value of one object to another, it should not be challenging to transfer the value into a freshly created object.
```
// Movable (equivalent to N3351 Movable):
template <class T>
concept bool Movable =
  MoveConstructible<T> &&
  Assignable<T, T&&>;

// Copyable (equivalent to N3351 Copyable):
template <class T>
concept bool Copyable =
  Movable<T> &&
  CopyConstructible<T> &&
  Assignable<T, T&> &&
  Assignable<T, const T&> &&
  Assignable<T, const T&&>;
```

Semiregular is simplified in syntax, but roughly equivalent to the prior definition:
```
template <class T>
concept bool Semiregular =
  Copyable<T> &&
  Constructible<T> &&
  requires(size_t n) {
    { new T[n] } -> Same<T*>;
  };
```

Instead of describing required *features* of object types, these concepts actually describe classes of useful object types. E.g., `Function` can be greatly simplified:
```
concept bool Function =
  CopyConstructible<T> &&
  requires (F f, Args...args) {
    typename ResultType<F, Args...>;
    { f(forward<Args>(args)...) } -> Same<ResultType<F, Args...> >;
  };
```
Refinement diagram for visualization:
![Subsumption diagram](https://docs.google.com/drawings/d/1OAp-2Bnnkm3NTOrt_yErp4FDSDeeW_E3g8bQGoROeGw/pub?w=230&h=308)

**Comment by ericniebler** [comment]
At first blush, I like it. Maybe @asutton can have a look and comment from the perspective as an author of n3351.

**Comment by CaseyCarter** [comment]
FWIW, I implemented this decomposition [on a range-v3 branch](https://github.com/CaseyCarter/range-v3/tree/decomposition). I had to make exactly four additional changes to fix the resulting breakage. Three were bugs exposed by the tighter constraints. The fourth was to constrain the common_pair/common_tuple constructors to allow "object or reference type constructible from Foo." I consider it a positive that "constructible object" and "constructible object or reference" have different names (even though the particular name I chose, `ConstructibleRef`, is pretty poor).

**Comment by asutton** [comment]
I meant to +1 this, but have been offline over the weekend. I think
it's fine and this decomposition becomes pretty obvious when you look
at containers.

Some other comments:

Cut this from destructible:

  ( &t } -> Same<T*>

I think the committee's advice is to use addressof if there's any
doubt that & does the wrong thing.

I think these can be cut too:

  delete p;
  delete[] p;

If a type is destructible, then deleting an object of that type should
be well formed. Maybe... I guess somebody could write private
destructors. But if we have syntactic requirements, we need semantic
requirements. The same goes for new expressions.

I don't think that these are meaningful.

  Constructible<T, const T&&>;
  Assignable<T, const T&&>;

Assuming you manage to pass an argument of that type, I think you
would want to end up with a copy (since you can't effectively move
from a const-qualified temporary).
Andrew Sutton

**Comment by ericniebler** [comment]
> I think the committee's advice is to use addressof if there's any doubt that & does the wrong thing.

If we succeed in banishing the need to sprinkle `addressof` all over STL implementations, I think we've done a service. Our advice should be: don't overload `operator&`, and if you do, don't expect the STL to work with your f***ed up type.

> I think these can be cut too:
>     delete p;
>     delete[] p;

`delete` and array `delete` are overloadable operators. I always took these requirements to mean, if they're overloaded, they should be sensible. There *should* be semantic requirements, I guess.

> I don't think that these are meaningful.
>     Constructible<T, const T&&>;
>     Assignable<T, const T&&>;

Sure. It's another way of saying a copy constructor. It's perfectly OK to say "`a = move(b)`" even if `b` is a const object. You end up with a `const T&&`, which you should be able to (copy) assign to `a`.

BTW, I really like this change. Casey, can you submit a pull request? Two actually: one for stl2 and one for ranges-v3. Thanks!

**Comment by asutton** [comment]
>
> I think the committee's advice is to use addressof if there's any doubt
> that & does the wrong thing.
>
> If we succeed in banishing the need to sprinkle addressof all over STL
> implementations, I think we've done a service. Our advice should be: don't
> overload operator&, and if you do, don't expect the STL to work with your
> f***ed up type.
>
Fair enough. We give the same advice for &&, ||, and !.

**Comment by CaseyCarter** [comment]
>> delete p;
>> delete[] p;

> delete and array delete are overloadable operators. I always took these requirements to mean, if they're overloaded, they should be sensible. There should be semantic requirements, I guess.

I think the new/delete requirements from N3351 are primarily to require that a user-defined new/delete operator be accessible. 

> `const T&&`

CopyConstructible and CopyAssignable in the Standard require assignment & construction from `const T&&` to cover rare corner cases in generic code where it happens; I see no reason not to keep it. 

> Our advice should be: don't overload operator&, and if you do, don't expect the STL to work with your f***ed up type.

Overload all you want, but return the address of the object when your overload finishes or STL doesn't want your stupid object. I'm sorely tempted to somehow forbid overloading the comma operator as well, at the very least for iterators. Having to write `++i, void(), ++j` in a double-sequence `for` loop is ridiculous. There's no syntax for it in Concepts, but a prose bullet that says "DON'T OVERLOAD THE COMMA OPERATOR FOR A TYPE YOU PASS TO THE LIBRARY, MORON" would be good enough for me.

> Casey, can you submit a pull request? Two actually: one for stl2 and one for ranges-v3.

Yes - I'll squash and rebase my range-v3 branch tomorrow morning, and get wording for stl2 in a day or two.

**Comment by ericniebler** [comment]
> Yes - I'll squash and rebase my range-v3 branch tomorrow morning, and get wording for stl2 in a day or two.

Best to hold off on the stl2 edits. I'll be submitting a massive patch in the next day or two regarding the colorized markup of diffs. No sense creating merge conflicts needlessly.

**Comment by ericniebler** [comment]
@CaseyCarter : OK, I've committed my big change to the diff markup. Please go ahead and submit a pull request for the changes to the object concepts. Thanks.

**Comment by ericniebler** [comment]
After seeing the trouble in range-v3, I suggest that allocation and deallocation move back to Semiregular. Thoughts?

**Comment by CaseyCarter** [comment]
The argument for "construction is equivalent to allocation":

By passing my type to a component that requires Constructible, I give that component the authority to create objects of my type. I shouldn't care if that component creates those objects on the stack, on the heap, as class members or array elements of some other object type, or through the use of an allocator. I should leave the author of that component the freedom to choose the most appropriate form of object creation for achieving the component's design goals.

If the "trouble" you refer to is the creation of the new concept for constraining the member variables of pair and tuple, I think it is very much a good thing that the value-semantic Constructible concept is insufficient to describe the requirements for a member variable that can be either a value-semantic subobject or a reference.

**Comment by ericniebler** [comment]
> I think it is very much a good thing that the value-semantic Constructible concept is insufficient to describe the requirements for a member variable that can be either a value-semantic subobject or a reference.

Ha! The question is whether `Constructible` should enforce value semantics. If we agree it should, then sure. I'm not there yet.

> By passing my type to a component that requires Constructible, I give that component the authority to create objects of my type. I shouldn't care if that component creates those objects on the stack, on the heap

One could argue that the concept one should use for this is `Semiregular`, not `Constructible`. I'm not sure yet where I stand.

**Comment by CaseyCarter** [comment]
Thoughts that occurred to me while developing wording:
* If array allocation is sensible for `Semiregular`, it should be sensible for `Constructible`. Once I've authorized generic code to create objects of my type, I shouldn't care how many objects it chooses to create and whether or not those objects are created individually or in an array. There's no syntax to constrain `new T[n]{{...}}` for arbitrary `n`, but `new T[1]` is sufficient to ensure the array allocation syntax is valid:

  ```
template <class T, class...Args>
concept bool Constructible() {
  return Destructible<T>() &&
    requires(Args&&...args) {
      T{forward<Args>(args)...};
      new T{forward<Args>(args)...};
      new T[1]{{forward<Args>(args)...}};
    };
}
```
This would make `Semiregular` be simply `Copyable<T>() && Constructible<T>()`, which I find elegant.
* The volatility requirement of `Semiregular` needs to be pushed further down the hierarchy, I believe all the way to `Destructible`. Much like the addressability requirement, non-volatility is fundamental to value-semantic object types. (Aside: "not volatile" is ironically enough insufficient to provide non-volatility. We need to somehow forbid even data-race-free simultaneous modification of objects. The library should be able to e.g. sort an array of objects containing `atomic<int>` but only if the user can guarantee that the call to sort is synchronized with any modifications of the objects.)
* After these changes, many of the "Core Concepts" are confusingly quite far removed from the core language wording. I consider reorganization to be outside my mandate, but it may simplify the presentation to reorganize the subsections of [concepts.lib] as:
  * Core: Same, Derived, Convertible, Common, the Integral family, Assignable, Swappable
  * Comparison: Boolean, EqualityComparable, TotallyOrdered
  * Value-Semantic/Object: Destructible, Constructible, Copy/MoveConstructible, Copyable, Movable, Semiregular, Regular
  * Function:  same

**Comment by ericniebler** [comment]
I think I'm OK with all of this. It's a pretty major change from what LEWG reviewed, though. When you make your pull request, can you take the rationale you wrote here and put it in a new appendix? Or maybe we should ask for an N number for a separate paper. This all need to be carefully explained. It would be best to have all our names on it: you, me, Andrew and Sean.

**Comment by asutton** [comment]
It's the same way I built the object model in Origin, so I'm okay with it.

There's probably one other semantic requirement to consider for default
construction, which might motivate one extra concept: for value-semantic
types, is the default value unique. Or, semantically, this:

 T{} equals T{}

I think so but I've heard arguments against (e.g., a "time
 class that default constructs to now() -- but I don't like that).

Andrew Sutton

**Comment by CaseyCarter** [comment]
> There's probably one other semantic requirement to consider for default
construction, which might motivate one extra concept: for value-semantic
types, is the default value unique. Or, semantically, this:

>  T{} equals T{}

If we add a requirement to the effect that the expressions used in concept definitions must by default be equality preserving, then that semantic *will* be required since `T{}` is an expression used in the definition of `Constructible<T>`. The effective requirement would be actually be stronger, requiring `T{args...}` equals `T{args...}` for *any* `args`. We would have to explicitly opt-out to avoid it. I'm also not a fan of non-regular (irregular?) default constructors, but I suspect there will be some dissenting viewpoints in the committee.

**Comment by CaseyCarter** [comment]
There's wording to bang on. I'll writeup a design rationale appendix for now, with the expectation that it may need to grow into a full paper later, and then push.

**Comment by ericniebler** [comment]
>> I think I'm OK with all of this.
> 
> Including the reorganization of the subsections of [concepts.lib]?

Sure.
