### ISSUE TITLE
What is the interaction between struct tagged and struct array?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#123]

**Comment by CaseyCarter** [comment]
Has there been any more discussion on this? We don't *require* `tagged_array`, but it's trivial to specify:

```c++
template <class T, std::size_t N, TagSpecifier...Tags>
  requires sizeof...(Tags) <= N
using tagged_array = tagged<std::array<T, N>, Tags...>;
```

I've had a [unit test for `tagged<array>`](https://github.com/CaseyCarter/cmcstl2/blob/master/test/tagged.cpp#L142) ever since implementing `tagged`, so I know there are no conflicts.

What are our conditions for moving this issue forward?

**Comment by ericniebler** [comment]
No conditions. I just hadn't done the experiment. It's easy to add if we're certain it's sensible.

**Comment by CaseyCarter** [comment]
No mention has been made of this in over a year (http://wiki.edg.com/bin/view/Wg21kona2015/RangesWordingReview2015-09-10). We've found no need for `tagged_array`, no one has expressed interest in `tagged_array`.

Closing this issue without prejudice.
