### ISSUE TITLE
Can we fix the std::swap-and-std::iter_swap-are-unconstrained problem non-intrusively?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#139]
I feel like *maybe* we can fix the problem with unconstrained overloads in `std` if we define overloads in `std::experimental::ranges::v1` like:

```c++
template <class ...Ts>
concept bool _Auto = true;

// Extension: less specialized than overloads on different Movable types.
template <Movable T, Movable U>
  requires Same<T, U>() && _Auto<T, U>
void swap(T& a, U& b)
  noexcept(noexcept(b = ranges::exchange(a, std::move(b)))) {
  b = ranges::::exchange(a, std::move(b));
}

// Poison the well:
template <class T, class U>
  requires _Auto<T, U>
void swap(T&, U&) noexcept = delete;
```

The idea is that since the second overload is "constrained", it will be preferred over the unconstrained version in namespace `std` ... but it's deleted so it can't be selected.

I've used the following type to test this out. It's not swappable, but it has `std` as an associated namespace. Without the poison-pill overload, the test fails. With it, it succeeds.

```c++
struct unswappable : std::string {
  unswappable() = default;
  unswappable(const unswappable&) = delete;
  unswappable(unswappable&&) = delete;
};
CONCEPT_ASSERT(!models::Swappable<unswappable&, unswappable&>);
```

Are there any problems I'm not seeing? If this works the way I think it does, then it's *much* easier for vendors to deliver stand-alone Ranges TS implementations without having to make corresponding hacks their stdlib implementations than I thought. I'm cautiously optimistic.

**Comment by CaseyCarter** [comment]
Why bother with `_Auto` instead of just requiring `true` directly? It's less to type and/or read and it's functionally equivalent. (In general, functionally-equivalent-but-not-equivalent treads dangerously near the ODR.)

I see nothing obviously wrong with this. It may be the last piece missing so that we can finally specify the N4381-style customization points. I'll do some investigation after Trick-or-Treating tonight and see if I can break it.

**Comment by CaseyCarter** [comment]
I am a bit perplexed as to why the test fails without the poison pill, since libstdc++'s `std::swap` is already constrained just as we require in the TS...

Oh, of course: there's a non-member overload of `swap` for `basic_string&` that is the best match when both our and libstdc++'s generic `swap` is not viable. `unswappable` is actually swappable in STL1 by slicing, so this is a breaking change. There are surely veneer types in the wild that wrap some additional interface around a `std` type and rely on this kind of slicing swap, so I wouldn't call it pathological. It does seem like a managable amount of breakage, though.

**Comment by CaseyCarter** [comment]
> actually swappable in STL1

Ok, this is wrong. It wouldn't be swappable if the generic overload was unconstrained as specified in C++14. It will be in C++17 when that constraint becomes required. So people relying on this have non-portable brokenish code already.

**Comment by CaseyCarter** [comment]
> The idea is that since the second overload is "constrained", it will be preferred over the unconstrained version in namespace std ... but it's deleted so it can't be selected.

This is not what is happening here. The deleted overload `swap(T&, U&)` is less specialized than `std::swap(T&, T&)` so it won't be preferred by overload resolution; the constraints on the deleted overload are not significant. What *is* happening is that `unswappable` doesn't meet the constraints if libstdc++'s `std::swap(T&, T&)`. `std::swap(basic_string&, basic_string&)` is viable - which allowed `unswappable` to be swappable in the first place - but it's a worse match than the deleted overload since it requires derived-to-base-class conversion which the deleted overload does not.

If `std::swap(T&, T&)` was not constrained, it would be preferred by overload resolution regardless of the presence of the less-specialized deleted overload. To beat it we would have to delete `swap(T&, T&)`, which re-introduces the problem that I worked around when I changed `swap`'s declaration to use two distinctly typed parameters. `swap(T&, T&)` is preferred to overloads of swap on distinct types like `swap(optional<T>&, optional<U>&)` when resolving `swap(optional<T>&, optional<T>&)`.

I think the lesser of the two evils here is to delete `swap(T&, T&)` and force writers of cross-type swaps to write a same-type overload as well.

**Comment by ericniebler** [comment]
I got it to work, and I don't like it. Here are the overloads:

```c++
    template <Movable T>
      requires true // NOTE WELL
    STL2_CONSTEXPR_EXT void swap(T& a, T& b)
      noexcept(noexcept(b = __stl2::exchange(a, __stl2::move(b)))) {
      b = __stl2::exchange(a, __stl2::move(b));
    }

    template <Movable T, Movable U>
      requires Same<T, U>() && true  // NOTE WELL
    STL2_CONSTEXPR_EXT void swap(T& a, U& b)
      noexcept(noexcept(b = __stl2::exchange(a, __stl2::move(b)))) {
      b = __stl2::exchange(a, __stl2::move(b));
    }

    // Extensions: Poison the well.
    template <class T>
      requires true
    void swap(T&, T&) = delete;
    template <class T, class U>
      requires true
    void swap(T&, U&) = delete;

    // ...

    template <class T, std::size_t N>
      requires __array_swap_test<T, T> && true
    STL2_CONSTEXPR_EXT void swap(T (&t)[N], T (&u)[N])
      noexcept(noexcept(__try_swap(*t, *u)));

    template <class T, class U, std::size_t N>
      requires __array_swap_test<T, U> && true
    STL2_CONSTEXPR_EXT void swap(T (&t)[N], U (&u)[N])
      noexcept(noexcept(__try_swap(*t, *u)));

    // Poison the well:
    template <class T, std::size_t N>
      requires true
    void swap(T (&t)[N], T (&u)[N]) = delete;
    template <class T, class U, std::size_t N>
      requires true
    void swap(T (&t)[N], U (&u)[N]) = delete;
```

Note that the "good" overloads must have a `&& true` constraint in order for them to not be ambiguous with the `= delete` versions. Trouble is, for a user to define their own constrained `swap`, they *also* must use `&& true` as a requirement *and* they must provide two overloads:

```c++
// Has a constrained swap findable via ADL:
struct constrained_swappable {
  constrained_swappable() = default;
  constrained_swappable(const constrained_swappable&) = default;
  constrained_swappable(constrained_swappable&&) = default;
};
template <class T>
concept bool ConstrainedSwappable =
  ns::Same<T, constrained_swappable>();
template <ConstrainedSwappable T, ConstrainedSwappable U>
  requires true
void swap(T&, U&) {}
template<ConstrainedSwappable T>
  requires true
void swap(T &, T &) {}
```

This sucks.

**Comment by CaseyCarter** [comment]
```c++
    template <class T> void swap(T&, T&) = delete;

    STL2_CONSTEXPR_EXT void swap(Movable& a, Movable& b)
      noexcept(noexcept(b = __stl2::exchange(a, __stl2::move(b)))) {
      b = __stl2::exchange(a, __stl2::move(b));
    }

    template <class T, class U, std::size_t N>
      requires __array_swap_test<T, U>
    STL2_CONSTEXPR_EXT void swap(T (&t)[N], U (&u)[N])
      noexcept(noexcept(__try_swap(*t, *u)));

    template <class T, std::size_t N>
      requires __array_swap_test<T, T>
    STL2_CONSTEXPR_EXT void swap(T (&t)[N], T (&u)[N])
      noexcept(noexcept(__try_swap(*t, *u)));
```
works with:
```c++
namespace ranges = std::experimental::ranges;

struct unswappable : std::piecewise_construct_t {
  unswappable() = default;
  unswappable(const unswappable&) = delete;
  unswappable(unswappable&&) = delete;
};
static_assert(!ranges::models::Swappable<unswappable&>);

// Has a constrained swap findable via ADL:
struct constrained_swappable {
  constrained_swappable() = default;
  constrained_swappable(const constrained_swappable&) = default;
  constrained_swappable(constrained_swappable&&) = default;
};
template <class T>
concept bool ConstrainedSwappable =
  ranges::Same<T, constrained_swappable>();
template <ConstrainedSwappable T, ConstrainedSwappable U>
void swap(T&, U&) {}
template<ConstrainedSwappable T>
void swap(T &, T &) {}
static_assert(ranges::models::Swappable<constrained_swappable&>);
```

**Comment by ericniebler** [comment]
How is the `=delete` swap not ambiguous with `std::swap` when `std::swap` is unconstrained?

**Comment by CaseyCarter** [comment]
That's a good question. I conjecture that it *is* ambiguous, but that's not a problem because it's intended to be broken. Lookup for `swap` should fail if a more specialized/constrained overload isn't found.

**Comment by CaseyCarter** [comment]
Simplified model:

```c++
#include <iostream>

namespace STD {
  template <class T>
  void foo(T&, T&) {
    std::cout << "Unconstrained STD::foo called\n";
  }

  struct fooable_type {};
  void foo(fooable_type&, fooable_type&) {
    std::cout << "STD::foo(fooable_type) called\n";
  }

  struct unfooable_type {};

  namespace nested {
    template <class T>
    void foo(T&, T&) = delete;

    template <class T>
      requires __is_same_as(T, int)
    void foo(T&, T&) {
      std::cout << "STD::nested::foo called\n";
    }

    template <class T>
      requires requires (T& t, T& u) { foo(t, u); }
    void do_foo(T& t) {
      foo(t, t);
    }
  }
}

struct my_fooable_type : STD::unfooable_type {};
void foo(my_fooable_type&, my_fooable_type&) {
  std::cout << "foo(my_fooable_type) called\n";
}

struct my_unfooable_type : STD::unfooable_type {};

int main() {
  int i;
  STD::nested::do_foo(i);

  STD::fooable_type t{};
  STD::nested::do_foo(t);

  long l;
  // STD::nested::do_foo(l); // Error as intended

  my_fooable_type m{};
  STD::nested::do_foo(m);

  my_unfooable_type u{};
  // STD::nested::do_foo(u); // Error as intended
}
```
In the requires clause for `do_foo(my_unfooable_type&)`, lookup for `foo(my_unfooable_type&, my_unfooable_type&)` finds both the deleted overload (unqualified name lookup) and the unconstrained `foo` in namespace `STD` (ADL). Since overload resolution fails due to ambiguity, `foo(t, u)` is not a valid expression.

**Comment by ericniebler** [comment]
Huh. That's certainly interesting for cmcstl2 and for anybody trying to ship a stand-alone implementation of the Ranges TS. Any thoughts on whether the Ranges TS should require this? Or leave it as-is (requiring std::swap to be constrained)? I don't much care for the fact that users may have to define two swap overloads in some cases.

**Comment by CaseyCarter** [comment]
> I don't much care for the fact that users may have to define two swap overloads in some cases.

Strongly agree. I think the endgame is to have `std::swap` and `std::iter_swap` be constrained just as `begin`, `end`, `size` and `empty` are now. To be clear: `swap` is almost certainly going to be constrained soon in the WP thanks to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4511.html, and constraining `iter_swap` is trivial once `swap` is constrained:
```c++
template <class ForwardIterator1, class ForwardIterator2>
auto iter_swap(ForwardIterator1& i1, ForwardIterator2& i2) ->
  decltype(swap(*i1, *i2));
```
so this isn't a high bar.

I'm inclined to put the deleted-overload-dance in the TS and remove the change to `std::swap` so that TS implementations can be as unintrusive and portable as possible. At the same time, we should submit a separate paper to constrain `iter_swap` in the WP. We can then remove the deleted-overload-dance from the TS when we update it to be relative to C++17 instead of C++14, which could possibly be a second TS version depending on when things actually ship. Or even better we can remove the dance when the TS is incorporated into the WP itself. At the same time I acknowledge that it's incredibly messy to have a transitional mechanism like this in the TS - at the very least we would need an addendum detailing exactly what is going on here and why. The level of subtlety involved in this technique is far beyond what we could clarify in a simple note.

If you think that's too heavy for a transitional mechanism - and I wouldn't argue the point - then we should constrain `std::iter_swap` appropriately in the TS and simply live with the fact that the TS can't be implemented perfectly alongside an unmodified C++14 standard library.

**Comment by CaseyCarter** [comment]
Another factor for the decision: The issue is broader than just `swap` and `iter_swap`. All of the customization points in cmcstl2 provide semantic guarantees stronger than those of the std versions and therefore need poison pills. `begin(r)` guarantees that the return value satisfies `Iterator`, `size(r)` returns `Integral`, `end(r)` satisfies `Sentinel<decltype(begin(r))>`, etc. whereas the std versions simply return whatever `r.member()` returns.

There's no reasonable way to constrain the range access customization points in std to enforce the TS semantics.

**Comment by ericniebler** [comment]
Do you want to take a stab at specifying this and the function-object customization points?

**Comment by CaseyCarter** [comment]
Yes, I've been planning to and letting other things get in the way. I'll get started on it.

**Comment by ericniebler** [comment]
If we want this change to be in the post-meeting mailing, it has to be done by the deadline, which is this Friday.

**Comment by ericniebler** [comment]
I'm calling this one done. Yay!
