### ISSUE TITLE
Boolean concept needs "contextextually" and short-ciruit

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#15]

**Comment by ericniebler** [comment]
@StephanTLavavej , I've been working on the Boolean concept. What do you think of this:

19.2.6 Concept `Boolean` [concepts.lib.corelang.boolean]
~~~~{cpp}
template <class B>
concept bool Boolean =
  requires(B b1, B b2) {
    bool(b1);          // explicit conversion to bool
    { b1 } -> bool;    // implicit conversion to bool
    b1 ? true : false; // contextual conversion to bool
    { !b1 } -> Boolean;
    {b1 && b2} -> Same<bool>;
    {b1 || b2} -> Same<bool>;
  };
~~~~~

The `Boolean` concept describes the requirements on a type that is usable in Boolean contexts.

Given values `b1` and `b2` of type `B`, then type `B` models `Boolean` if and only if

1. `bool(b1) == (b1 ? true : false)`.
2. `bool(b1) == [](bool x) { return x; }(b1)`.
3. `bool(b1) == !bool(!b1)`.
4. `(b1 && b2)` is semantically identical to `(bool(b1) && bool(b2))`, including short-circuit evaluation.
5. `(b1 || b2)` is semantically identical to `(bool(b1) || bool(b2))`, including short-circuit evaluation.

*[ Example:* The types `bool`, `std::true_type`, and `std::bitset<>::reference` are `Boolean` types. *end example ]*

**Comment by StephanTLavavej** [comment]
There's no need to require both explicitly convertible and contextually convertible. See 4 [conv]/4.

Are b1 and b2 permitted to be different types? For example, you need to require that both WeirdBool && WeirdBool, and WeirdBool && bool, don't trigger overloading.

Otherwise, this looks good to me.

**Comment by CaseyCarter** [comment]
* Implicit conversion to T implies explicit conversion, and as STL said *contextual conversion* simply means the the language sometimes performs explicit conversions for you.
* N4377 [dcl.spec.concept]/3: "The definition of a function concept or the initializer of a variable concept shall not include a reference to the concept being declared." So `{ !b1 } -> Boolean;` is ill-formed within the definition of `Boolean`.
* Is "short-circuit evalution" defined in the standard?

**Comment by ericniebler** [comment]
> So `{ !b1 } -> Boolean;` is ill-formed within the definition of `Boolean`.

Yeah, I figured.

> Is "short-circuit evalution" defined in the standard?

No, but it's used. ;-)

**Comment by StephanTLavavej** [comment]
Implicitly convertible does *not* imply explicitly convertible. It's possible for them to have different meanings. (Definitely if both the source and destination are classes. I'd have to think about whether this applies to bool destinations.)

**Comment by CaseyCarter** [comment]
>Implicitly convertible does not imply explicitly convertible. It's possible for them to have different meanings. (Definitely if both the source and destination are classes. I'd have to think about whether this applies to bool destinations.)

I should have said "for well-behaved types, implicit conversion implies explicit conversion." One of the major benefits of Concepts is enabling us to specify exactly what we consider to be well-behaved types, so that we can write generic code that doesn't have to workaround every possible pathological behavior. I would be happy to throw out types that are implicitly convertible but not explicitly convertible much as we have types that are copy constructible but not move constructible (CopyConstructible requires MoveConstructible) or types that define `&` to return something other than the address of the object (Semiregular requires `{ &t } -> Same<T*>` and `&t == addressof(t)`). 

Ironically enough, I already did so without thinking about pathological types. I've been using:
```
template<class T, class U>
concept bool ExplicitlyConvertible =
  Same<T, U> || requires(T t) { static_cast<U>((T&&)t); };

template<class T, class U>
concept bool Convertible =
  Same<T, U> ||
  (ExplicitlyConvertible<T, U> && std::is_convertible<T, U>::value);
```
so that Same subsumes Convertible and Convertible subsumes ExplicitlyConvertible.
