### ISSUE TITLE
Kill unsigned integers throughout STL2

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#182]
They were arguably a mistake in STL1. Investigate how difficult the change would make migration from STL1.

**Comment by dhaumann** [comment]
Can you elaborate? Are you talking about size_t being everywhere right now, making things like this error prone:

for (int i = 0; i < my_vector.size() - 1; ++i) {...} // note the problematic case for size() == 0

**Comment by ericniebler** [comment]
The fact that `.size()` returns an unsigned integer and iterators' difference type is required to be signed pretty much guarantees that there will be signed/unsigned mismatches in simple and sane uses of the STL. It's a mess. We should use signed integers everywhere that bit-twiddling isn't required.

**Comment by atrops** [comment]
I prefer the unsigned type because it signs that a negative index is not sane for a container. We're working with indices and an index has to be null or positive for a container. At a pointer you might operate with an offset, which must be signed.
A signed type connote that a size might be negative. An access to operator[] with a negative value might be correct. That is incorrect for a container based on indices. This is perfectly documented by a type which cannot be negative.
An unsigned index type does not need to be checked if it is positive. Of course it is.

If you want to iterate through a container execpt the last element you have to ask if there is a last element: if( my_vector.size() >= 1 ) for (int i ....
First: this documents what you want to do, what you expect. If there are enough elements for the following job, then do...
Second: You put two information into one a size value: It's used as the size of the vector (which might be 0) and additional as an implicit condition for your special task ("it must be at least 1").
To put these together you need a signed type. For my point of view, you want to weaken the restrictions of a type to imply preconditions. For me it looks like a hack. I really like hacks, but we should use a hack if it is necessary and not in simple for-loops.

So I disagree.

**Comment by ericniebler** [comment]
> I prefer the unsigned type because it signs that a negative index is not sane for a container.

This was the prevailing wisdom when the STL was first designed. But logically, a count of things need not be positive. I may want to keep a count in a signed integer to denote the number of elements either added to or removed from a collection. Then I would want to combine that with the size of the collection. If the size of the collection is unsigned, now I'm forced to mix signed and unsigned arithmetic, which is a bug farm. Compilers warn about this, but because the design of the STL pretty much forces programmers into this situation, the warning is so common that most people turn it off. That's a shame because this hides real bugs.

Use of unsigned ints in interfaces isn't the boon many people think it is. If by accident a user passes a slightly negative number to the API, it suddenly becomes a huge positive number. Had the API taken the number as signed, then it can detect the situation by asserting the number is greater than or equal to zero.

If we restrict our use of unsigned ints to bit twiddling (e.g., masks) and use signed ints everywhere else, bugs are less likely to occur, and easier to detect when they do occur.

**Comment by atrops** [comment]
> But logically, a count of things need not be positive.
That is true. If two persons are in an elevator and three leave one person must enter the elevator to get it empty. That's logic, but it's not a common use case for any kind of containers I know.

If my software supports such a logic I explicitly have to check before I use such a number is an valid index and explicitly say "This is an index".

>  I may want to keep a count in a signed integer to denote the number of elements either added to or removed from a collection.
This value is not an index. If you want to use it in another way, you should explicitly document it.

I think you can only add a positive number of elements to a container as you can remove only a positive amount of elements from a container. If you have 2 elements in a container and remove -1 elements to get 3 elements in the container you are doing something which is absolutely logical. 
But I don't see that anyone would teach this to students as a good programming style.
So I don't see why to open that door.

> Compilers warn about this ...  the warning is so common that most people turn it off. 
From my point of view this is the interesting point: This should not be a warning. It should be an error.
If I turn off that warning I implicitly say I want to fuck this up. I see this like c-style casts: You can do it that way, but then it's just crap.
I don't see a way to stop suicide developers.

> If by accident a user passes a slightly negative number to the API, it suddenly becomes a huge positive number. 
Same answer as before: If something can happen by accident it should not compile.
Lets say we have multiple derivation and there is a method in both bases C++ does not compile, because it is not clear which method is meant. We also could say we implicitly take the method of the first base offering this symbol. But we have to be explicit, because otherwise we can call the wrong function by accident. 

Promoting a (negative) signed int implicitly to an unsigned is a bad idea from my point of view. I think we should discuss a switch to turn off this error only for compatibility reasons and deliver a warning instead. And I think we should not use that switch.

> Had the API taken the number as signed, then it can detect the situation
If I have a container of 2 billion entries and get -1 as index which is unsigned 4 billion or greater, than I can also detect that the given index is not valid easily.
I don't see the advantage. A slightly negative number is always a huge positive number. 

> If we restrict our use of unsigned ints to bit twiddling (e.g., masks) and use signed ints everywhere else, bugs are less likely to occur, and easier to detect when they do occur.
Why that?

If you access to an index -1 instead of index 4 billion it's the same bug. You don't get less bugs and in both cases it is still obviously that the index is invalid and even why. If you calculate an index in a way that the result can be negative you did it wrong. And you did the same mistake if you have a huge unsigned number. Why should STL react in another way as it would if the index is too huge? The developer makes a mistake and has to debug.

I absolutely see your point that there are people that ignore warnings. That also happens on highways when wrong-way drivers ignore warning signs. But I never saw a special lane for wrong way drivers on the left. It's not the use case. A broken car is a use case, therefore you have a emergency lane on the right.
Here in germany automated roadblocks are currently discussed for people ignoring the warnings signs. This can happen by accident but the result of a roadblock is that your car will not be executed in the wrong direction. You cannot even start driving on a highway.
From my point of you: if you put in int into a unsigned int api you should be stopped instead of promoted.

Also driving backwards is a logical option on a highway. But we don't accept that on a highway: Driving backwards is not a valid use case here. This usually ends in a crash.
This is the reason why we teach driving students not access a highway with a negative speed towards the direction of the highway.
I don't see that we have another logic here.

Maybe my point of view is out of date. That is absolutely a valid option. But so far I think signed indices are trying to build a ghost drivers lane, but I think stop people promoting ints into indices is more valuable. They represent completely different things and if we are sure that the value of an int can be used as an index, I think, we should say this explicitly.


To be honest: I don't even like unsigned ints. I would prefer to see them wrapped as container<T>::index.

**Comment by poelmanc** [comment]
> They were arguably a mistake in STL1

I think it's actually very widely agreed that using unsigned types for sizes in STL was a mistake. [This 2013 panel](https://channel9.msdn.com/Events/GoingNative/2013/Interactive-Panel-Ask-Us-Anything) of C++ gurus including Bjarne Stroustrup, Andrei Alexandrescu, Herb Sutter, Scott Meyers, Chandler Carruth, Sean Parent, Michael Wong, and Stephan T. Lavavej universally agreed that it was a mistake; see the discussions at [12:12-13:08](https://www.youtube.com/watch?v=Puio5dly9N8#t=12m12s), [42:40-45:26](https://www.youtube.com/watch?v=Puio5dly9N8#t=42m40s), and [1:02:50-1:03:15](https://www.youtube.com/watch?v=Puio5dly9N8#t=1h2m50s). I particularly like the brevity and frankness of that last bit.

[Google's style guide](https://google.github.io/styleguide/cppguide.html#Integer_Types) says "In particular, do not use unsigned types to say a number will never be negative." Stroustrup echos the same thoughts above.

I realize this sounds like argument from authority, but I just think they state the reasons better than I could.

When I make the argument myself, it's about the frequency of unsigned integers leading to buggy code. Using unsigned types is like dancing right at the edge of a cliff. All integer types can wrap past their limits due to mathematical operations, and such behavior is rarely desired. With signed types, those _danger zones_ are far away from typical values, whereas with unsigned types the _danger zone_ is right next to the most commonly used value of all, 0. This leads to bugs, as Stroustrup indicated in the middle segment above when he said unsigned types are highly error prone.

**Comment by cjdb** [comment]
While I am a proponent for killing unsigned types in STL2, I do wonder what will happen when you need to allocate (and reference) more memory than the largest possible signed number.

**Comment by atrops** [comment]
@poelmanc: _"When I make the argument myself, it's from my experience of the frequency of unsigned integers leading to buggy code. Using unsigned types is like dancing right at the edge of a cliff."_

You do. But not being allowed to cross the zero border means you have the same cliff with ints than I have with unsigned ints. You just take a rope that you don't get any pain if you fall one single unit to far. I fall across the universe. Applications often don't survive that.

A crashing application is a great sign for a developer that there might be a bug, also an application running in a almost never ending loop is a great and easy to understand signal for a developer.

Which means I realize quite early if I fall and crash. After realizing I correct my code. Creating bugs is a normal process while programming. Realizing them is the art. Getting a clear signal if you make a mistake is positive from my perspective.

But you don't need to crash to have an advantage: Being some billion units away from any expected result is easier to realize than being one single unit away from the correct result. You don't need to calculate everything by hand to find out, you just have a look and you know: We have a bug here and you also know what kind of bug it is.

So I have to correct my code and your code produces a result as expected. That does not mean that your code is more correct than mine. It just might mean you haven't realized that your code is producing an result in the expected area but unfortunately not the correct result.
I think about that cliff when coding all the time, because I got shot through the universe. I don't want that. Which means that my code usually don't shot me across the universe. I don't think that I do more bugs than you. I only think I realize it more often if I do. In fact I believe that I avoid a lot of bugs by avoiding the negative side of integers.

While going to a 64 bits Version I removed all "int" used as index in our software and replaced them with std::size_t. Due to this I made 2 bugs in a quite big software. One was found before it was even committed. At the other I misunderstood the magic that happened there before.
But I found more than a dozen bugs nobody knows about so far. After about 15 of the same type I stopped counting.
Algorithms got clearer because "int" where often used in bizarre ways. Without encoding states in -1 and calculating values on top of a valid index or flying above the "-1"-cliff you have to tell what should happen in that algorithm. You don't use "size = v.size()-1; ... if( size >= 1 ) v[size]...". I replaced it with "size = v.size(); ... if( size >= 2 ) v[size-1]..." which means that the algorithm need 2 or more elements in a vector and not ( s-1 >= 1 ) and you use the last element.
You check your necessary preconditions before you start calculating.
Often the algorithm got a better structure because indices which became less than 0 in the beginning of an algorithm were not calculated anymore. The algorithm got another structure. Initially it was examined if we are in the situation where we need to calculate that index, which includes the fact that it cannot be less than 0. Then we calculated it. Otherwise it never appears. Therefore we wrote a the condition why(!) we need that index instead of using the potentially negative value of the index to decide if we will need it or if we have to correct it later for a special case.
This kind magic contains several errors.

I believe not putting this kind of magic into an integer makes my code less buggy. I don't even try it, because an unsigned type is not able to handle it. There will be a boolean which have a name that also describes what I am doing here and why.

A common mistake were functions like "int doSomethingAndTellMeTheIndexOrMinusOne(...)" to "bool doSomethingAndTellMeTheIndex( ..., std::size_t & result )". Its result was used several times as an index without any checking. So everytime it was used in that way it was a potential bug.
You cannot use that value immediately anymore. Of course you can ignore the boolean result, but that's not done by mistake anymore. If the result you're asking for is not the result of the function, the result of the function might be important.

Additionally our benchmark told us that our software got faster up to 15%. I guess a lot of that speed is the result of the fact that I removed all conditions like if( x < 0 ). 


Let me say this in other words: I like that cliff the way it is. If divides the universe into two halfspaces at index zero. Which means half of the bugs I can make will result in values which will be easily identified as nonsense and often produce clear signals like a segmentation fault or (almost) endless loops.

But of course we can try an STL with ptrdiffs. If the panels says so, they are the experts. Let's see if the world becomes better then. 
I put my money on the unsigned indices. 

Not because you can mix them up with integers but because you can stop that (as I said, I would prefer an unsigned container::index type).

Whenever someone initializes an unsigned integer with -2 it is not the failure of the unsigned int, escpecially if that unsigned int should be used as an index. I am sorry, but I do not see Bjarnes Stroustrups argument.  Even thinking that a bug because of such a behaviour is the failure of the language is wrong in my point of view.
Who calls himself a developer must know that you don't initialize a gun by holding it towards your foot. And if not, the gun is not responsible if the developer gains some pain. If the gun is responsible than next time the developer will hold the gun against his head and confidently shot himself thinking that someone else has thought out that shooting yourself in the head cannot be dangerous. The job of the developer is to understand what he is doing and explain that to the machine. Bringing a language to a level that the developer is not responsible to understand what he is doing will not result in less bugs.

I am wondering why you can compile 'unsigned int bla = -2' without a warning - even with -Wall. Why should someone do assign -2 to uint without explicit reinterpret cast? This signs clearly that someone makes a mistake or he has to clearify that he understands what he is doing.
The danger is implicit casting. The failure Stroustrup describes has been happen before that value is used as an index.
If that developer really wants the bit pattern where rightmost bit is turned off, he could use ~1, so it is also easier to read what should happen compared to -2. A negative number should not be valid for uint types. Stroustrups example how to misuse unsigned int is not the sign that uint is wrong, it's the sign that C++ is unable to tell a developer that he is mixing up things.
Therefore we need to depreciate implicit castings instead of creating a woolly STL.
If mixing up stuff is done implicitly you get bugs. Stop it and you get less bugs. Therefore an STL is better which differs between indices for containers and offsets (ptrdiffs) for pointers (like C-arrays are) and takes care that you don't mix this up (which can be done by container<>::index or by deprecating implicit casts in C++).

**Comment by poelmanc** [comment]
> I do wonder what will happen when you need to allocate (and reference) more memory than the largest possible signed number.

@cjdb @CaseyCarter As Stroustrup said at  [42:40-45:26](https://www.youtube.com/watch?v=Puio5dly9N8#t=42m40s) and Carruth echoed: "If you need an extra bit, I am really reluctant to believe you" and "Use the next larger signed type." When we reach the point where we need more than 2^63 bytes, we're basically also at the point where we need more than 2^64 bytes, and at that point we'll be using 128-bit integers.

**Comment by cjdb** [comment]
> An error, much like what happens today on many (most?) implementations when you try to allocate 1ULL << 63 bytes.

> As Stroustrup said at 42:40-45:26 and Carruth echoed: "If you need an extra bit, I am really reluctant to believe you" and "Use the next larger signed type."

Very much agreed, and your reasoning following is quite sound as well! I think I misunderstood the definition of `size_t`, thinking that it could be 4 bytes on a system that can address >4GB memory. If this isn't a possibility, no further concerns.

**Comment by ubsan** [comment]
I don't understand the argument made here. It's basically saying, "we don't want invariants to be specified in the type system". Which is... really weird, from a C++ perspective. One of the big things about C++ is type safety, and invariants in the type system as opposed to in comments (*cough* RAII). Why would we want to change that for this specific thing?

**Comment by viboes** [comment]
I believe must work with unsigned types when the values can not be negative. This is where  types help us. The problem is that builtin unsigned types have modulo arithmetic and converts from signed types.  

Wondering if we don't need an strong unsigned integer type that has undefined behavior on overflow/underflow and that doesn't converts from signed types.

This type could have as underlying type a signed type, so that we avoid modulo arithmetic, but will delete conversion constructors from signed.

Of course it will be better if this type was defined by the language and not as a library.

**Comment by poelmanc** [comment]
@ubsan Unsigned doesn't enforce any invariant on int, it defines an interpretation of the bit pattern. Enforcing an invariant would require run-time checks on every numeric operation. As @viboes proposes, that could be readily accomplished with a new class, which anyone is free to write. Said constrained_int< min, max > class could even enforce an arbitrary range (e.g. maintain the invariant that the int is always between 0 and 100, or -10 to +10, etc.) Enforcing that invariant comes at a run-time cost so folks would only want to use it where necessary, but I agree such a type would be useful.

The problem is that many people think of unsigned int as maintaining an invariant, when what it really does is modulus arithmetic, and as all these C++ luminaries point out at [12:12-13:08](https://www.youtube.com/watch?v=Puio5dly9N8#t=12m12s), [42:40-45:26](https://www.youtube.com/watch?v=Puio5dly9N8#t=42m40s), and [1:02:50-1:03:15](https://www.youtube.com/watch?v=Puio5dly9N8#t=1h2m50s), that leads to buggy code. Subtraction causes bugs, and you can't assert or check that the desired "invariant" has been maintained, because 4294967295 is a valid value for an unsigned int.

**Comment by DrPizza** [comment]
Types represent a domain, and for object counts, Some subset of ℕ<sub>0</sub> is the correct domain, with the subset being driven by the size of machine.

Difference types (including `ptrdiff_t` and everything on up) are generally broken anyway (with usual representations a difference type needs to be one bit bigger than a size type). 32-bit systems with >2<sup>31</sup> addressable bytes are widespread (64-bit Windows, Linux, and macOS all allow the use of 32-bit applications with >2GB addressable). Address space fragmentation might make a 3GB `vector` tricky on such platforms, but a 3GB `deque<char>` is reasonable. Encouraging the use of broken difference types does not feel like a step forward.

This is especially true given that signed types are a bomb waiting to explode thanks to optimizations. "Oh, your signed arithmetic wrapped around? Thanks for the undefined behaviour, I'll just optimize this routine in a way that's perverse, even though the underlying hardware behaves in the logical way." Right now, nobody should be using signed types at all, because it's too easy to write stuff that doesn't behave according to any reasonable expectations.

If you want to do signed types everywhere then at the very least signed types need to be cleared up. Give us checked arithmetic, give us defined overflow rules (if you can't live with "every platform is 2's complement" then at least make it platform-dependent; the vast majority of us only write on such platforms and we really don't care if our code is unportable when moved to DSPs or mainframes).

Or better yet: give us better tools for defining domains. Let me have, say, an index type that's bounds checked by the size of its corresponding container in debug builds. Let me have a defined-wraparound signed type that operates with all the machine's efficiency. Let me selectively have checked arithmetic.

And let us disable the implicit conversions (and, while we're at it, C-style casts...).

**Comment by ericniebler** [comment]
Changing the language semantics regarding signed overflow, or adding new integral types to the core language, are not within the purview of the Ranges/STL2 work. Making STL2 work with integral wrappers that enforce invariants *is* within scope, and it's something we could conceivably do, though probably not before the Ranges TS is finalized.

@poelmanc wrote:
> The problem is that many people think of unsigned int as maintaining an invariant, when what it really does is modulus arithmetic

Yes, this exactly.

**Comment by DrPizza** [comment]
> Changing the language semantics regarding signed overflow, or adding new integral types to the core language, are not within the purview of the Ranges/STL2 work. 

I didn't imagine so, but that's why I'm not keen on making us make greater use of signed types. C++ has many traps for the unwary, and even the conscientious programmer falls into them from time to time.  As things stand right now, signed types have additional pitfalls that unsigned types do not, and I think that these pitfalls are both more subtle and more dangerous than whatever problems unsigned types have.

**Comment by ericniebler** [comment]
Given the way random-access iterators work, we can't avoid the use of signed integers in the STL; iterator difference _must_ give a signed integral type since it can be negative. The status quo --
 mixed signed and unsigned arithmetic -- is the worst of all possible world, because it makes the problem pervasive. I much rather accept the potential for UB that comes with signed over-/underflow. With a 64-bit signed difference type, the actual occurrence of that over-/underflow is likely to be far less frequent than the over-/underflow that comes with "promoting" a signed negative value into an unsigned positive one.

**Comment by ubsan** [comment]
I would rather use something like @foonathan's `type_safe` library. Getting rid of type-safety because of implicit casts seems like... well, there are better ways to do it.

**Comment by ericniebler** [comment]
This position seems somewhat extreme to me. Shall we all stop using `int` in our programs because `int` can overflow and lead to UB? Shall we change the signature of `main` to return a type-safe integer wrapper? My God, it's a wonder planes aren't falling from the sky as we debate this. ;-)

**Comment by mechacrash** [comment]
So we shouldn't stop using int regardless of issues... But we should stop using unsigned? :P

I think that you're fixing one set of problems and creating another, and the idea of better accommodation for user error (because, if you're ever underflowing your unsigned in the case of an index / count / etc - you're doing something wrong!) shouldnt be a consideration for this - It would be a nice side effect.

I'd say a constrained integral type is the right way to go. You dodge issues present with both int and unsigned and it's more expressive to the user what it is you're using that value to do. If that's not practical in time for STL2/ranges, then unsigned (the norm) should be maintained just for ease of migration.

**Comment by foonathan** [comment]
> Given the way random-access iterators work, we can't avoid the use of signed integers in the STL; iterator difference must give a signed integral type since it can be negative. The status quo --
mixed signed and unsigned arithmetic -- is the worst of all possible world, because it makes the problem pervasive.

I totally agree, that's why I created `index_t` and `distance_t_t`: https://github.com/foonathan/type_safe/blob/master/include/type_safe/index.hpp
These are basically iterators, but without the dereferencing. And `index_t` is an unsigned integer type, that supports all random access iterator position advancements (increment/decrement, add `distance_t`, subtract `distance_t`, subtract two `index_t` yielding `distance_t`) and `distance_t` is the signed counterpart representing distances between indices. Obviously, they're non convertible.
This allows only sane operations for indices. If you want to do anything else (multiplication, division), you're no longer dealing with indices directly, but doing arithmetic on integers. And that needs to be reflected, by explictly casting to an (signed/unsigned, as you wish) integer type.

I'm going to give a [C++Now talk]()https://cppnow2017.sched.com/event/b082f55f666921f81ce106bba76cc747 outlining the design decisions there in more detail, so this was just a quick overview.

> Shall we all stop using int in our programs because int can overflow and lead to UB?

On the contrary, `unsigned` under/overflow should be UB as well.

> Shall we change the signature of main to return a type-safe integer wrapper? 

We should totally change the signature of main, but that's a different story.

> This position seems somewhat extreme to me.

(I'm interpreting "this position" as "using classes instead of integers".)
Is it extreme though? For decades, people used a plain integer type to represent time, now we've got `std::chrono`. I think it's only logically to take what was done there and apply it on more fields.

**Comment by ericniebler** [comment]
> So we shouldn't stop using int regardless of issues... But we should stop using unsigned? :P

I didn't say that. Unsigned is useful when you need to manipulate bits or when you want modulo arithmetic.

> I think that you're fixing one set of problems and creating another

I don't deny it. I like to think I would be replacing a common error with an uncommon one. If one choice were obviously correct, it would have been made long ago. The problems with the STL's use of mixed signed/unsigned integer types have only manifested over time.

> I'd say a constrained integral type is the right way to go.

It's one way to go, and facilitating that decision is an interesting research area.

Runtime-constrained integral types are not a panacea though. For many uses, including generic ones, the performance cost of a test-and-branch for every integer operation would be too high. But I agree the user should have that choice.

> This allows only sane operations for indices. If you want to do anything else (multiplication, division), you're no longer dealing with indices directly, but doing arithmetic on integers.

A type as simple as a striding iterator needs to be able to multiply and divide iterator differences.

> > This position seems somewhat extreme to me.
>
> (I'm interpreting "this position" as "using classes instead of integers".) 

No, I meant the position that built-in signed integral types are to be avoided everywhere because of the potential for over-/underflow. Unsigned types are no better in this regard because often the user doesn't want or expect wrap-around. Just because the behavior is defined doesn't mean it's right.

**Comment by foonathan** [comment]
> A type as simple as a striding iterator needs to be able to multiply and divide iterator differences.

That can be solved by adding another type `stride_t` (or something like that, just coming up with it) which allows multiplication. Or by casting to int, then back.

> No, I meant the position that built-in signed integral types are to be avoided everywhere because of the potential for over-/underflow. Unsigned types are no better in this regard because often the user doesn't want or expect wrap-around. Just because the behavior is defined doesn't mean it's right.

I agree to that, in fact I'd love to have UB unsigned integer types, which is what I was trying to get in type_safe and what `index_t` is by default.

**Comment by thiagomacieira** [comment]
> While I am a proponent for killing unsigned types in STL2, I do wonder what will happen when you need to allocate (and reference) more memory than the largest possible signed number.

That cannot happen, by definition. `ptrdiff_t` is defined as being a signed integer type with range sufficient to represent the subtraction between two pointers in the same array (= same memory block). Therefore, the largest contiguous memory block possible is limited by both `ptrdiff_t`'s and `size_t`'s range. This also ensures that for any given two pointers `a` and `b` (in the same array), `a < b → a - b < 0`.

The operating system may support allocating larger memory blocks, but the language does not support that.

Non-contiguous containers like `std::deque<std::byte>` could have more elements than `ptrdiff_t`'s range, but I don't think this is sufficient motivation.

**Comment by ericniebler** [comment]
Now that stl2 is dead, I can't see anything coming from the desire to transition away from unsigned size types in the Standard Library. It was a nice dream while it lasted.

**Comment by MikeGitb** [comment]
> Now that stl2 is dead, I can't see anything coming from the desire to transition away from unsigned size types in the Standard Library. It was a nice dream while it lasted.

So sad, but if `std::span` really manages to retain a signed size/index type, wouldn't it be reasonable to do the same for views, even if this is incompatible with the rest of std? particular if ranges/views live in their own sub-namespace?

**Comment by ubsan** [comment]
I would argue that it's incredibly unreasonable to break compatibility with the vast majority of written code at this point.

**Comment by MikeGitb** [comment]
@ubsan:Sorry, I miss-worded that. It wouldn't break compatibility in any way, just wouldn't follow the established practice, just like std::span (we are talking about new types anyway).

**Comment by ericniebler** [comment]
New types don't get to live in a bubble, though. Especially if they are designed to be usable in generic contents.

**Comment by ubsan** [comment]
@MikeGitb It breaks compatibility with generic algorithms, and user expectations.

**Comment by MikeGitb** [comment]
@ubsan:
> It breaks compatibility with generic algorithms, 

Such as/how? If you have some examples, you might want to talk to the authors of `std::span` or rather the authors behind http://open-std.org/JTC1/SC22/WG21/docs/papers/2018/p1089r0.pdf (which proposes to switch to an unsigned size type for span) . If this is a common problem they probably want to add it as another argument for their proposal.

**Comment by ubsan** [comment]
@MikeGitb Any algorithm which takes a range and assumes that `size(c)` returns an unsigned type (which works for all standard containers).

**Comment by MikeGitb** [comment]
@ubsan: I'm probably dense: can you please show a concrete example? I have written a few algorithms that work on any random access container and none requires size to be unsigned or signed. I've also written wrappers for (almost) every standard library algorithm, such that it takes a range instead of a pair of iterators (nowhere near as sophisticated as ranges-v3) and all of them work perfectly well with signed size types.

**Comment by ubsan** [comment]
@MikeGitb 

```
template <typename T>
void print_container(std::ostream& os, T const& container) {
  if (container.empty()) {
    os << "{ }";
  else {
    os << "{ ";
    for (std::size_t i = 0; i < container.size() - 1; ++i) {
      os << container[i] << ", ";
    }
    os << container[container.size() - 1] << " }";
  }
}
```

is a simple example - it's not super modern C++-y, but it's valid at this point, and would become a signed-unsigned comparison with `span`.

**Comment by MikeGitb** [comment]
@ubsan: That example is perfectly valid c++ code with signed sizes. The signed unsigned comparison might be not be ideal, but that is a far cry from "an algorithm that assumes size being unsigned".

**Comment by poelmanc** [comment]
Most collection classes such as std::vector document their size() functions as returning T::size_type. So rather than assuming that every T's size() returns std::size_t, the code should instead should read:

`for (typename T::size_size i = 0; i < container.size() - 1; ++i) {`

Or this could be a great place to use `auto`. Either solution would eliminate signed/unsigned comparisons as well as errors due to values being stored in objects that are too small. So this is not a reason to stick with the past mistake of using unsigned integers.

**Comment by ubsan** [comment]
@poelmanc more code has been written than will be written in C++, as the committee likes to say - it might not be the prettiest, but it works for all existing contiguous containers.

`auto` will use `int`, which is clearly wrong.

@MikeGitb do you not turn on warnings in your code? My compiler errors when I do that comparison...

**Comment by euloanty** [comment]
So stupid.

> Most collection classes such as std::vector document their size() functions as returning T::size_type. So rather than assuming that every T's size() returns std::size_t, the code instead should read:
> 
> `for (typename T::size_type i = 0; i < container.size() - 1; ++i) {`
> 
> Or this could be a great place to use `auto`. Either solution would eliminate signed/unsigned comparisons as well as errors due to values being stored in objects that are too small. So this is not a reason to stick with the past mistake of using unsigned integers.
> 
> The two `size() - 1` lines also scream "danger!" Sure, in this code they're properly guarded by `if (container.empty())`, but that's a great example of the type of code that Stroustrup refers to as error-prone when using unsigned integers.

You are wrong. Why not just write this?
for (std::size_t i = 0; i+1 < container.size(); ++i)

**Comment by ericniebler** [comment]
> So stupid.

If you can't be kind, keep it to yourself.

**Comment by euloanty** [comment]
> > So stupid.
> 
> If you can't be kind, keep it to yourself.

Anyone who advocates signed integers deserves this.

**Comment by askoldilvento** [comment]
> 
> You are wrong. Why not just write this?
> for (std::size_t i = 0; i+1 < container.size(); ++i)

Just because on another day you need a reverse walk. 

`for (std::size_t i = container.size() - 1; i >= 0; --i)`

And in case an empty container instead of the noop you get a boom. Singed int is not a true group, but it is much closer to a group than unsigned int. Working with a group is always simpler than with a set where half of the operations are illegal.

**Comment by iddm** [comment]
> > You are wrong. Why not just write this?
> > for (std::size_t i = 0; i+1 < container.size(); ++i)
> 
> Just because on another day you need a reverse walk.
> 
> `for (std::size_t i = container.size() - 1; i >= 0; --i)`
> 
> And in case an empty container instead of the noop you get a boom. Singed int is not a true group, but it is much closer to a group than unsigned int. Working with a group is always simpler than with a set where half of the operations are illegal.

In the case of a reverse walk, use `int` (or `isize`-analogue from Rust). It is your code. And to make you happy they invented these (ugly, in my opinion) iterators, so you'd not end up writing code like you've written above most of the time. Also, if we are talking about the size of a container, we should never return signed, as we then will also have to check for it being negative as well. And by logic, size can't be negative.

If we get back to original comment:

> The fact that .size() returns an unsigned integer and iterators' difference type is required to be signed pretty much guarantees that there will be signed/unsigned mismatches in simple and sane uses of the STL. It's a mess. We should use signed integers everywhere that bit-twiddling isn't required.

The problem is exactly that the `difference_type` should be unsigned as well while it's not. It should represent `difference` or `distance` which can never be negative. There aren't shoes of size `-XS`. If you compare the distance from a to b and then from b to a you'll never use negatives, you'll always say like "from a to b it is 5 kilometres, and from b to a it is also 5 kilometres". Having this `difference_type` as signed actually what is causing confusion and problems. There should be another type called "offset", then it should be allowed to have negative values, like `offset from a to b is 5 items while offset from b to a is -5 items (as we are moving backwards)".

**Comment by expnkx** [comment]
> > > You are wrong. Why not just write this?
> > > for (std::size_t i = 0; i+1 < container.size(); ++i)
> > 
> > 
> > Just because on another day you need a reverse walk.
> > `for (std::size_t i = container.size() - 1; i >= 0; --i)`
> > And in case an empty container instead of the noop you get a boom. Singed int is not a true group, but it is much closer to a group than unsigned int. Working with a group is always simpler than with a set where half of the operations are illegal.
> 
> In the case of a reverse walk, use `int` (or `isize`-analogue from Rust). It is your code. And to make you happy they invented these (ugly, in my opinion) iterators, so you'd not end up writing code like you've written above most of the time. Also, if we are talking about the size of a container, we should never return signed, as we then will also have to check for it being negative as well. And by logic, size can't be negative.
> 
> If we get back to original comment:
> 
> > The fact that .size() returns an unsigned integer and iterators' difference type is required to be signed pretty much guarantees that there will be signed/unsigned mismatches in simple and sane uses of the STL. It's a mess. We should use signed integers everywhere that bit-twiddling isn't required.
> 
> The problem is exactly that the `difference_type` should be unsigned as well while it's not. It should represent `difference` or `distance` which can never be negative. There aren't shoes of size `-XS`. If you compare the distance from a to b and then from b to a you'll never use negatives, you'll always say like "from a to b it is 5 kilometres, and from b to a it is also 5 kilometres". Having this `difference_type` as signed actually what is causing confusion and problems. There should be another type called "offset", then it should be allowed to have negative values, like `offset from a to b is 5 items while offset from b to a is -5 items (as we are moving backwards)".

That is not true.

auto it(vec.cbegin()+3),it1(vec.cbegin()+1);
it-it1 < 0

**Comment by expnkx** [comment]
for (std::size_t i(vec.size());i--;);

singed integers are harmful.

**Comment by expnkx** [comment]
BTW. signed integers fanboys (which are mostly idiots) have lost the battle. std::span proves yea! std::size_t now.

**Comment by expnkx** [comment]
I would argue the subscriptor type should be operator[](std::integral value) which is a concept, instead of using a certain type since it might decrease performance with static_cast.

**Comment by expnkx** [comment]
BTW. If you want a general case for reverse traversal.

for (std::size_t i(vec.size()-1);i<vec.size();i-=2);

KISS

**Comment by ericniebler** [comment]
> signed integers fanboys (who are mostly idiots)

User @expnkx is now banned from any and all of my repositories. I have zero tolerance for abusive content like this.
