### ISSUE TITLE
Is IndirectlyMovableStorable underconstrained?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#187]
I want to add the following to the specification of `IndirectlyMovableStorable`:

3. Let `i` be a dereferenceable object of type `In`, let `o` be a 
dereferenceable object of type `Out`. Then `IndirectlyMovable<In, Out>()`
is satisfied if an only if
(3.1) -- If `Out` satisfies `Readable`, the expression `*o` has the same value after either `*o = iter_move(i)` or `*o = value_type_t<In>(iter_move(i))`.

@CaseyCarter Thoughts?

**Comment by CaseyCarter** [comment]
Since `rvalue_reference_t<In>` is the same type as `decltype(iter_move(i))`, `*o = iter_move(i)` is constrained to have those semantics by `IndirectlyMovable<In, Out>()` which requires `Writable<Out, rvalue_reference_t<In>>()`.

`*o = value_type_t<In>(iter_move(i))` is derivable from `IndirectlyMovableStorable<In, Out>()`. It requires both `Writable<Out, value_type_t<In>>()` and `Constructible<value_type_t<In>, rvalue_reference_t<In>>()`.
