### ISSUE TITLE
Do we need concept StrictWeakOrdering ?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#19]

**Comment by asutton** [comment]
There's no way to syntactically differentiate between a SWO and a
Relation (binary predicate). Same for Equivalence Relation. The
differences are all semantic.

I find useful to call them out by name in requirements, but purely for
the purpose of conveying their semantic intent.

So, technically no. But possibly for reasons of conveying information?

Andrew Sutton

**Comment by ericniebler** [comment]
That's the thought. Similarly, there is no syntactic difference between `Function` and `RegularFunction`, but the Palo Alto report defines them both anyway. I'm pretty indifferent on this one.

**Comment by asutton** [comment]
As long as were consistent with these decisions, then it's okay.

Andrew Sutton

**Comment by cartec** [comment]
I'm very much in favor of different names for concepts that differ only in semantics. Prose description of semantics is hard to remember and requires a thorough reading of the documentation. A named concept that appears directly in the declaration of a function is much more concise. 

In particular, N4382 has "The relation `R` must represent a strict weak ordering. [ Note: When `less<>` is used as the relation, the value type must model `TotallyOrdered`.—end note ]" in three different places, and "For algorithms other than those described in 25.4.3 to work correctly, `comp` has to induce a strict weak ordering on the values." in another. I think it would improve the quality of the specification to have a single definition of the concept `StrictWeakOrder` so that those semantics can be incorporated with a single word instead of an entire paragraph of prose.

**Comment by sean-parent** [comment]
We associate semantics with names and as long as the semantics are
different the names of the concepts should be - even if that isn't
enforceable. Much the same as we distinguish between operator== and
operator< by name only. Saying that a function requires a binary-predicate
doesn't convey that the predicate must provide a strict-weak-order.

Sean

**Comment by ericniebler** [comment]
Section [alg.sorting] in the standard has this to say about all the sorting algorithms:

> For algorithms other than those described in 25.4.3 to work correctly, `comp` has to induce a strict weak ordering on the values.

25.4.3 are the binary search algorithms: `lower_bound`, `upper_bound`, `equal_range`, and `binary_search`. The above seems to suggest these algorithms do not require a strict weak ordering relation, but the Palo Alto report disagrees. It reads:

> The binary search algorithms define a family of related operations on sorted data. All of these
algorithms in this section have an implied precondition that their input ranges `[first, last)` are
sorted either by the total ordering of their value types or with respect to the given (strict) weak
ordering.

I'm going with the Palo Alto constraints, but I'd like to understand why the current standard says what it does. Thoughts, anyone? @asutton? @sean-parent?

**Comment by sean-parent** [comment]
The comp for these algorithms is a bit odd in that we allow asymmetric
comparisons since we don't have projections. The requirement is that the
comparison portion be strict-weak (otherwise I don't know what these
algorithms mean) and that the range be sorted by the same comparison. Don't
know how the current wording ended up in the standard - maybe it was a
"punt" to allow the asymmetric compare?
