### ISSUE TITLE
Define UniformRandomNumberGenerator concept

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#22]

**Comment by cartec** [comment]
Suggested wording. Change `shuffle` declarations:

>```
// 25.3.12, shuffle:
template<RandomAccessIterator I, Sentinel<I> S, class Gen>
  requires Permutable<I> && UniformRandomNumberGenerator<remove_reference_t<Gen>> &&
    Convertible<ResultType<Gen>, DifferenceType<I>>
I shuffle(I first, S last, Gen&& g);

>template<RandomAccessIterable Rng, class Gen>
  requires Permutable<I> && UniformRandomNumberGenerator<remove_reference_t<Gen>> &&
    Convertible<ResultType<Gen>, DifferenceType<I>>
IteratorType<Rng> shuffle(Rng& rng, Gen&& g);
```

Since `shuffle` takes a URNG by forwarding reference, `Gen` will deduce an lvalue reference type when passed an lvalue argument. We want to constrain the type of the referred object, not the type of the reference - [see this post to the Concepts SG mailing list](https://groups.google.com/a/isocpp.org/forum/#!topic/concepts/GW2aNZSZ1jo) - hence `remove_reference_t<Gen>`. Unless someone has a better idea for constraining forwarding references, of course.

Add [rand.req.urng] replacing the entire contents of the same section in the standard:

>```
template <class G>
concept bool UniformRandomNumberGenerator =
  requires(G g) {
    typename ResultType<G>;
    { g() } -> Same<ResultType<G>>;
    requires UnsignedIntegral<ResultType<G>>;
    typename G::result_type;
    requires Same<ResultType<G>, G::result_type>;
    { G::min() } -> Same<ResultType<G>>;
    { G::max() } -> Same<ResultType<G>>;
  };
```

> Let `g` be any object of type `G`. Then type `G` models `UniformRandomNumberGenerator` if and only if
- Both `G::min()` and `G::max()` are constant expressions.
- `G::min() < G::max()`.
- `(G::min() <= g() <= G::max()) != false`.

> Remarks: A uniform random number generator `g` of type `G` is a function object returning unsigned integer values such that each value in the range of possible results has (ideally) equal probability of being returned. [ Note: The degree to which `g`’s results approximate the ideal is often determined statistically. —end note ]

**Comment by CaseyCarter** [comment]
Given `ResultType<G>`, `G::result_type` is redundant and harder to type (`typename G::result_type`) when the type is dependent. I'm inclined to remove `G::result_type` from the concept but leave it in the models - the random number engines - for backwards compatibility.
