### ISSUE TITLE
Incomplete edit to InputIterator to support proxy iterators

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#307]
The proxy iterators paper (P0022) made essential changes to the `Readable` concept to support proxy iterators but neglected to make a similar necessary edit to `InputIterator`. The `InputIterator` concept is currently requiring that the expression `*ci`, where `ci` is a `const`-qualified `InputIterator` `I`, is convertible to `const value_type_t<I>&`. This requirement is unsatisfiable for some proxy iterator types.

Consider a zip range with a reference type `pair<unique_ptr<int>&, int&>` and a value type `pair<unique_ptr<int>, int>`. There is no valid conversion from the former type to the latter since it would require copying a `unique_ptr`.

### Proposed resolution

Adopt the wording in [P0541](http://wg21.link/P0541).

**Comment by CaseyCarter** [comment]
To elaborate a bit: Before P0022, this requirement of `InputIterator` established the fundamental relationship between the reference and value types of an input iterator. P0022 relaxed the requirement to `CommonReference<reference_t<I>, value_type_t<I>&>()` and pushed it down into `Readable` since value type is a fundamentally a property of `Readable`.
