### ISSUE TITLE
Expression stability requirement ignores the existence of volatile

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#329]
[concepts.lib.general.equality]/3 describes that equality preserving expressions must be _stable_:

> Expressions required by this specification to be equality preserving are further required to be stable: two evaluations of such an expression with the same input objects must have equal outputs absent any explicit intervening modification of those input objects.

This is impossible if the expression inputs are `volatile`. Suggest adding an exception for inputs whose types are `volatile`-qualified. 

Proposed Resolution
--------------------

Change [concepts.lib.general.equality]/3 as follows:

```diff
 Expressions required by this specification to be equality preserving
 are further required to be stable: two evaluations of such an expression
 with the same input objects must have equal outputs absent any explicit
-intervening modification of those input objects.
+intervening modification of those input objects, provided that the types
+of the input objects are not `volatile`-qualified.
```

**Comment by ericniebler** [comment]
Refs #155

**Comment by CaseyCarter** [comment]
This is very much by design. We cannot support even the most basic equational reasoning without value stability. If `volatile` objects are not required to be value stable, then nearly every library component that uses the concepts will need to explicitly forbid `volatile` object types. How do we `sort` a sequence of values that is changing? How do we copy a `vector` of objects that is changing?

When this wording was written, we made a choice to *allow* `volatile`-qualified types under the auspice that their values are "subject to change by an external agent but not while an algorithm is examining them." The other perfectly sound choice - which N3351 took - is to outlaw `volatile`-qualified types altogether. I speculate that our approach is slightly more convenient for users of volatile types: they can use the range algorithms on volatile sequences if they can somehow guarantee stability of those sequences during the call.

**Comment by ericniebler** [comment]
My think-o dawned on my during my run just now. Sorry for the noise.
