### ISSUE TITLE
"x C++ Standard" in index

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#391]
At the beginning of the index, we have 
```
x C++ Standard, 2
```

**Comment by CaseyCarter** [comment]
I also think:

> "The Palo Alto", 2

needs to be fixed.

**Comment by timsong-cpp** [comment]
[intro.refs]: "N3351 is called the “The Palo Alto” report". Note the "the The".

And why are N4128 and N3351 normative references anyway?

**Comment by CaseyCarter** [comment]
> And why are N4128 and N3351 normative references anyway? They aren't normatively cited.

I agree that they are not "indispensable for the application of this document," although they do certainly provide design rationale and historical information to enrich understanding of the TS. I think we could get by with Bib references for those papers rather than normative references. As to **why** they are normative references, in my position as project editor I will fall back on longstanding political practice and blame the previous administration.

**Comment by timsong-cpp** [comment]
> I agree that they are not "indispensable for the application of this document," 

And if we use [the updated introductory text](https://github.com/cplusplus/draft/commit/13dd486bf478a9f3c02bd45297bab003df1ee935) like the IS ("the following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document"), then it's even clearer that they belong in the bib rather than the normative reference section.

> in my position as project editor I will fall back on longstanding political practice and blame the previous administration

LOL. That works.
