### ISSUE TITLE
Whither contiguous iterators?

### ISSUE THREAD

**Issue by ericniebler** [ericniebler/stl2#397]
Does the Ranges TS need to add support for contiguous iterators? They're a C++17 thing, and the TS targets C++14, but still.

**Comment by CaseyCarter** [comment]
Absent means of detecting contiguous iterators and/or converting non-dereferenceable contiguous iterators to pointers I think there isn't much we can usefully do. Sure, we can define a new category tag for contiguous iterators which is useful for people implementing their own containers, but if the Ranges library cannot tell that `std::vector`/`std::string`/`std::array`/`std::string_view` have contiguous iterators there doesn't seem to be enough benefit to justify the feature.

**Comment by CaseyCarter** [comment]
Wearing my STL implementer hat instead of my cmcstl2 implementer hat:

We could require implementations to specialize `experimental::ranges::iterator_category` to `contiguous_iterator_tag` for the `(const_)?iterator` types of `std::vector`/`std::string`/`std::array`/`std::string_view`/`std::valarray` that are not pointers. This couldn't be implemented portably, but would be simple for standard library implementers. We would still lack a mechanism to convert potentially-non-dereferenceable iterators to pointers, but it's always possible to convert a *pair* of contiguous iterators `[i, j)` into the pointer range/`span` `[j - i ? &*i : nullptr, (j - i ? &*i : nullptr)  + (j - i))`. [Notably, this is yet another occurrence of "it's easier to adapt a range than an iterator" which is quickly becoming a rule of thumb.]

A PR for this would be fairly low-impact on the TS WP:
* add `contiguous_iterator_tag`/`ContiguousIterator` to the `<e/r/iterator>` synopsis
* Add Contiguous to the places in [iterator.requirements.general] that name and/or count the iterator categories
* writeup a subsection specifying that `ContiguousIterator` refines `RandomAccess`, has the proper tag, and steal the requirement from C++17 [iterator.requirements.general]/6 "for integral values `n` and dereferenceable iterator values `a` and `(a + n)`, `*(a + n)` is equivalent to `*(addressof(*a) + n)`"
* throw a paragraph somewhere near the `iterator_traits` specification stating that `iterator_category_t</*...the things from std listed  above...*/>` is `contiguous_iterator_tag`
* change the "`begin(range)` returns a pointer" case of the `data` CPO to `begin(range) satisfies `ContiguousIterator`" ([range.primitives.data]/1.3)

I think this would be a satisfactory implementation of contiguous iterators for the TS. That said, this is a new feature / needs a paper / would have to go through LEWG. It's probably too late even if we don't finalize the TS in Toronto. This is low-hanging fruit for a TS2.

**Comment by ericniebler** [comment]
Done.
