### ISSUE TITLE
Mapping mechanism from tag specifier to tagged getter should be specified.

### ISSUE THREAD

**Issue by tomaszkam** [ericniebler/stl2#42]
In the current version of the Range TS, the mapping from the tag specifier to the tagged getter is left as the implementation detail, according to $20.2.6.3 [taggedtup.tagged] p5:
 > A _tag specifier_ is a type that facilitates a mapping from a tuple-like type and an element index into a _tagged getter_ that gives named access to the element at that index. The types in the `Tags` parameter pack shall be tag specifiers. The tag specifiers in the `Tags` parameter pack shall be unique. [ Note: The mapping mechanism from tag specifier to tagged getter is unspecified. — end note ]

As consequence the design provides no portable way to define user defined _tag specifiers_ and limits use of tagged tuples in the programs, by providing only limited set of tag specifiers, that are used for algorithms return type. That limitation putS in question the generality of the proposed component. 

As the editor explicitly stays that the intent of this section is to provide general purpose utility:
> [Editor’s note: This type exists so that the algorithms can return pair- and tuple-like objects with named accessors, as requested by LEWG. Rather than create a bunch of one-off class types with no relation to pair and tuple, I opted instead to create a general utility. I’ll note that this functionality can be merged into pair and tuple directly with minimal breakage, but I opted for now to keep it separate.]

I propose to standardize the mapping from _tag specifier_ to _tagged getter_, to allow creation of user defined tags. The simplest solution would be to define that specialization of `tagged_getter<TagSpecifier, ElementIndex>` to be used as _tagged getter_.

**Comment by ericniebler** [comment]
> That limitation putS in question the generality of the proposed component.

It's a fair point, but I prefer to wait to see what the committee thinks of this facility. In all likelihood, this whole thing will be seen as overreaching, and I'll need to yank it out.

**Comment by CaseyCarter** [comment]
Update on what's happened with this issue in the last five months:

During LWG review everyone has been happy enough with `tagged` as a way to return pairs/tuples from algorithms with nicely named field accessors, so we're reasonably certain the facility will stay in the TS. I mentioned during one of the review telecons that several people have expressed interest in a specified mapping from tag specifiers to tag getters so that the set of tag names can be user-extensible. I was prepared to write wording to do just that, having recently specified the `TagSpecifier` and `TaggedType` concepts that are now used to constrain `tagged` et al, and devised [a flexible mapping design](https://github.com/CaseyCarter/cmcstl2/blob/master/include/stl2/detail/tagged.hpp#L194) in which a getter is simply a class template that inherits from its single parameter `Base` and provides "name" functions that delegate to `Base::get`.

Consensus in the telecon was to leave the mapping unspecified for now to allow implementors freedom  to experiment and gain experience with the new feature. Given how useful it is to extend the set of tag types, I think it's extremely likely that the mapping will be specified either in a future version of the TS or when the TS becomes standardized.

**Comment by ericniebler** [comment]
Frankly, I think the committee was being over-cautious in this case. But since it saved me work, I didn't argue. :-) If someone were to champion the issue (in a small paper, perhaps?) there probably wouldn't be much resistance to specifying the mechanism. What is in the TS now meets my immediate needs, so I don't care much one way or the other.

**Comment by CaseyCarter** [comment]
Closing without prejudice.
