### ISSUE TITLE
[iterator.output] misuses std::forward

### ISSUE THREAD

**Issue by timsong-cpp** [ericniebler/stl2#494]
>     *i++ = std::forward(t); 

Also, `Iterator<I> && Writable<I, T> &&` has two sub-requirements on the same line, instead of different lines like `InputIterator`.

Proposed Resolution
-----------------------
Change the definition of concept `OutputIterator` in [iterators.output] as follows:
```diff
 template <class I, class T>
 concept bool OutputIterator =
-  Iterator<I> && Writable<I, T> &&
+  Iterator<I> &&
+  Writable<I, T> &&
   requires(I i, T&& t) {
-    *i++ = std::forward(t); // not required to be equality preserving
+    *i++ = std::forward<T>(t); // not required to be equality preserving
   };
```

**Comment by CaseyCarter** [comment]
This is the direct manifestation of a markup error in P0547R2: the source is `std::forward<T>(t)` instead of `std::forward&lt;T>(t)`.

We've also been gradually drifting away from the "one-term-per-line" layout for concepts. This happened first in the implementations as we gained familiarity with the syntax, and has leaked through into the spec in places. I'll switch this occurrence back to "one-term-per-line," but future versions of the document will probably stop using that style and instead consistently use a different style.

**Comment by CaseyCarter** [comment]
Thanks once again, Tim.
