### ISSUE TITLE
ranges::value_type is ill-formed for std::span

### ISSUE THREAD

**Issue by tcbrindle** [ericniebler/stl2#562]
In P0896R1, `ranges::value_type` has specialisations for types with nested typedefs `T::value_type` **or** `T::element_type`. If a type provides *both* nested typedefs however, the specialisations are ambiguous and `ranges::value_type` is ill-formed (confirmed by @CaseyCarter on Slack).

Unfortunately, this is exactly the case for `std::span` as of N4750.

Possible resolution:

Add a requirement along the lines of 

> If both `T::value_type` and `T::element_type` are defined, then they shall satisfy `Same<typename T::value_type, remove_cv_t<typename T::element_type>>`. Otherwise `ranges::value_type<T>` shall have no nested `type`.

On the other hand, a simpler alternative would be to just ignore `T::element_type` if `T::value_type` is defined, since the latter is more "range-y".

**Comment by ericniebler** [comment]
No doubt @CaseyCarter is nodding somewhere saying "I told you so" to himself. But I see this as yet another example of `span`'s basic confusion about what it is.

Logically, `ranges::value_type` is for computing the associated `value_type` of `Readable` types; that is, types that define unary `operator*`. It looks for nested `::value_type` for iterators, and it looks for nested `::element_type` because of smart pointers. (The Ranges TS gives arrays a `value_type` because you can apply `operator*` to them; they behave like pointers.) `span`, so far as I know, is not a `Readable` type so I don't feel any strong need to make this well-defined.

Any author of an iterator or a smart pointer type that defines both a `::value_type` _and_ a `::element_type` is doing something weird and should have to say -- by specializing `ranges::value_type` -- how it satisfies the `Readable` concept.

(This is made more clear in P1037, which renames `ranges::value_type<T>::type` to `ranges::readable_traits<T>::value_type`.)

**Comment by CaseyCarter** [comment]
P0896R1 [range.iterator.assoc.types.value_type]/1:

> A `Readable` type has an associated value type that can be accessed with the `value_type_t` alias template.

supports Eric's assertion that this is not a bug - `ranges::value_type_t` doesn't need to work with types like `span` that aren't intended to satisfy `Readable`.

[range.back.insert.iterator], [range.front.insert.iterator] and [range.insert.iterator] use `value_type_t<Container>` where `Container` is *not* required to satisfy `Readable`. (`Container` is unconstrained: the intent is that it meets the sequence container requirements / optional sequence container requirements for which we don't (yet) have corresponding concepts.) This usage suggests that `value_type_t` is intended to be usable for an unspecified class of non-`Readable` types. For the record, this usage in the insert iterators was an LWG suggestion; at the time we had no good reason *not* to replace `typename Container::value_type` with `value_type_t<Container>`. If there's confusion about the intended use of `value_type_t`, it's confusion of our own making ;)

I concur with Eric's assessment that the design intent of `value_type_t` is to be an associated type trait for the `Readable` concept, as the P1037 design makes clear. The bug that needs to be fixed here is the misuse of `value_type_t` in the specification of the insert iterators in P0896.

**Comment by ericniebler** [comment]
P1037 fixes that oversight.

**Comment by CaseyCarter** [comment]
> P1037 fixes that oversight.

Yes, by striking the insert iterators in `std::ranges`. I'd nevertheless like to correct the usage in P896 to be consistent with the design intent.

**Comment by ericniebler** [comment]
> > P1037 fixes that oversight.
> 
> Yes, by striking the insert iterators in `std::ranges`.

... and by not repeating the mistake to the insert iterators in `std`, and by renaming `value_type<>` to `readable_traits<>` and `value_type_t<>` to `iter_value_t<>`.
