### ISSUE TITLE
Algorithms that return bool

### ISSUE THREAD

**Issue by cjdb** [ericniebler/stl2#569]
Should algorithms that return `bool` (and only `bool`) be changed to return an iterator too? I don't have a use-case, but it might be beneficial to do something akin to:

```cpp
// highly contrived example
auto [result1, first] = all_of(begin(v), next(begin(v), 5), [](auto const& i) { return i == 0; });
auto [result2, _] = any_of(first, end(v), [](auto const& i) { return i != 0; });
return result1 and result2;
```

**Comment by CaseyCarter** [comment]
I'd say no. `all_of(r, p)`, `any_of(r, p)` and `none_of(r, p)` are respectively equivalent to:
* `find_if(r, not_fn(p)) == end(r)`
* `find_if(r, p) != end(r)`
* `find_if(r, p) == end(r)`
which makes these algorithms the thinnest of conveniences for people who don't want to be bothered with comparing to `end` because they only care about the resulting `bool` value. If you need an iterator to the exemplar element, just call `find_if` directly. Your example becomes:
```c++
auto pred = [](auto const& i) { return i != 0; };
auto mid = next(begin(v), 5)
auto first = find_if(begin(v), mid, pred);
return first != mid && any_of(first, end(v), pred);
```
